apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}db-migrator-config
type: Opaque
stringData:
  tern.conf: |-
    [database]
    host = {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
    port = {{ .Values.db.port }}
    database = {{ .Values.db.database }}
    user = {{ .Values.db.user }}
    password = {{ .Values.db.password }}

    [data]
    loadSampleData = {{ .Values.dbMigrator.loadSampleData }}
