{{- if .Values.hub.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.hub.serviceAccount.automountServiceAccountToken }}
{{- end }}
