{{- if .Values.hub.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
automountServiceAccountToken: {{ .Values.hub.serviceAccount.automountServiceAccountToken }}
{{- end }}
