apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}tracker-config
type: Opaque
stringData:
  tracker.yaml: |-
    restrictedHTTPClient: {{ .Values.restrictedHTTPClient }}
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      database: {{ .Values.db.database }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    creds:
      dockerUsername: {{ .Values.creds.dockerUsername }}
      dockerPassword: {{ .Values.creds.dockerPassword }}
    images:
      store: {{ .Values.images.store }}
    events:
      trackingErrors: {{ .Values.events.trackingErrors }}
    tracker:
      concurrency: {{ .Values.tracker.concurrency }}
      repositoryTimeout: {{ .Values.tracker.repositoryTimeout }}
      repositoriesNames: {{ .Values.tracker.repositoriesNames }}
      repositoriesKinds: {{ .Values.tracker.repositoriesKinds }}
      bypassDigestCheck: {{ .Values.tracker.bypassDigestCheck }}
