apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}tracker-config
type: Opaque
stringData:
  tracker.yaml: |-
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      database: {{ .Values.db.database }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    tracker:
      concurrency: {{ .Values.tracker.concurrency }}
      repositoriesNames: {{ .Values.tracker.repositoriesNames }}
      repositoriesKinds: {{ .Values.tracker.repositoriesKinds }}
      imageStore: {{ .Values.tracker.imageStore }}
      bypassDigestCheck: {{ .Values.tracker.bypassDigestCheck }}
      events:
        trackingErrors: {{ .Values.tracker.events.trackingErrors }}
      githubToken: {{ .Values.tracker.githubToken }}
