{{- if .Values.trivy.enabled | and .Values.trivy.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}trivy
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trivy.persistence.size | quote }}
  {{- if .Values.trivy.persistence.storageClassName }}
  storageClassName: {{ .Values.trivy.persistence.storageClassName }}
  {{- end -}}
{{- end -}}
