apiVersion: v2
name: hub
description: Hub Helm chart
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: postgresql
    version: 8.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
