postgresql.enabled: true
nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
pullPolicy: IfNotPresent

log:
  level: info
  pretty: false

db:
  host: hub-postgresql.default.svc.cluster.local
  port: "5432"
  database: hub
  user: postgres
  password: postgres

hub:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  service:
    type: NodePort
    port: 80
  deploy:
    replicaCount: 1
    image:
      repository: tegioz/hub
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
  server:
    basicAuth:
      enabled: false
      username: hub
      password: changeme

chartTracker:
  image:
    repository: tegioz/chart-tracker
  numWorkers: 50
  repositories: []
  imageStore: pg

dbMigrator:
  image:
    repository: tegioz/db-migrator
  loadChartRepositories: true

# Values for postgresql chart dependency
postgresql:
  image:
    repository: postgres
    tag: 12
  persistence:
    mountPath: /data
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: hub
  postgresqlDataDir: /data/pgdata
