nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
pullPolicy: IfNotPresent

log:
  level: info
  pretty: false

db:
  url: postgres://postgres@192.168.64.1:5432/hub

hub:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  service:
    type: NodePort
    port: 80
  deploy:
    replicaCount: 1
    image:
      repository: tegioz/hub
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
  server:
    basicAuth:
      enabled: true
      username: hub
      password: changeme

chartTracker:
  image:
    repository: tegioz/chart-tracker
  numWorkers: 50
  repositories: []
