nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
imageTag: latest
pullPolicy: IfNotPresent

log:
  level: info
  pretty: false

db:
  host: hub-postgresql.default.svc.cluster.local
  port: "5432"
  database: hub
  user: postgres
  password: postgres

hub:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  service:
    type: NodePort
    port: 80
  deploy:
    replicaCount: 1
    image:
      repository: artifacthub/hub
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  server:
    baseURL: ""
    basicAuth:
      enabled: false
      username: hub
      password: changeme
    cookie:
      hashKey: default-unsafe-key
      secure: false
    oauth:
      github:
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - read:user
          - user:email
      google:
        clientID: ""
        clientSecret: ""
        redirectURL: ""
        scopes:
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile
    limiter:
      enabled: false
    xffIndex: 0
  email:
    fromName: ""
    from: ""
    replyTo: ""
    smtp:
      host: ""
      port: 587
      username: ""
      password: ""
  analytics:
    gaTrackingID: ""

falcoTracker:
  cronjob:
    image:
      repository: artifacthub/falco-tracker
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  concurrency: 10
  repositories: []
  imageStore: pg
  bypassDigestCheck: false

helmTracker:
  cronjob:
    image:
      repository: artifacthub/helm-tracker
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  numWorkers: 50
  repositories: []
  imageStore: pg
  bypassDigestCheck: false

olmTracker:
  cronjob:
    image:
      repository: artifacthub/olm-tracker
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  concurrency: 10
  repositories: []
  imageStore: pg
  bypassDigestCheck: false

opaTracker:
  cronjob:
    image:
      repository: artifacthub/opa-tracker
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  concurrency: 10
  repositories: []
  imageStore: pg
  bypassDigestCheck: false

dbMigrator:
  job:
    image:
      repository: artifacthub/db-migrator
  loadSampleData: true

# Values for postgresql chart dependency
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 12
  persistence:
    mountPath: /data
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: hub
  postgresqlDataDir: /data/pgdata
