nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
imageTag: latest
pullPolicy: IfNotPresent

log:
  level: info
  pretty: false

db:
  host: hub-postgresql.default.svc.cluster.local
  port: "5432"
  database: hub
  user: postgres
  password: postgres

hub:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  service:
    type: NodePort
    port: 80
  deploy:
    replicaCount: 1
    image:
      repository: cncf/hub
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  server:
    basicAuth:
      enabled: false
      username: hub
      password: changeme
    cookie:
      hashKey: default-unsafe-key
      secure: false
  email:
    fromName: ""
    from: ""
    replyTo: ""
    smtp:
      host: ""
      port: 587
      username: ""
      password: ""


chartTracker:
  cronjob:
    image:
      repository: cncf/chart-tracker
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  numWorkers: 50
  repositories: []
  imageStore: pg

dbMigrator:
  job:
    image:
      repository: cncf/db-migrator
  loadSampleData: true

# Values for postgresql chart dependency
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 12
  persistence:
    mountPath: /data
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: hub
  postgresqlDataDir: /data/pgdata
