baseURL: /docs
languageCode: en-us
title: Artifact Hub documentation
theme: "hugo-geekdoc"
publishdir: ../../web/build/docs
build:
  noJSConfigInAssets: false
  useResourceCacheWhen: fallback
  writeStats: false
markup:
  goldmark:
    extensions:
      typographer: false
params:
  AuthorName: Artifact Hub Team
  geekdocSearch: false
  geekdocAnchorCopy: false
