linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
  fast: false

linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  goconst:
    min-occurrences: 5
  revive:
    rules:
      - name: unused-parameter
        disabled: true
