linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
  fast: false

linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  goconst:
    min-occurrences: 5

service:
  golangci-lint-version: 1.33.x
