version: 2

project_name: ah

release:
  name_template: "Artifact Hub {{ .Tag }}"
  header: |
    Please see the [changelog](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=changelog) for more details.

changelog:
  disable: true

snapshot:
  version_template: "devel-{{ .ShortCommit }}"

builds:
  - id: ah
    binary: ah
    main: ./cmd/ah
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.gitCommit={{ .FullCommit }}

archives:
  - id: ah
    files:
      - LICENSE
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

dockers_v2:
  - id: ah
    dockerfile: cmd/ah/Dockerfile
    images:
      - artifacthub/ah
      - public.ecr.aws/artifacthub/ah
    tags:
      - "{{ .Tag }}"
      - latest
    build_args:
      VERSION: "{{ .Version }}"
      GIT_COMMIT: "{{ .FullCommit }}"
    labels:
      "org.opencontainers.image.description": "Artifact Hub command line tool"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .CommitDate }}"
      "org.opencontainers.image.documentation": "https://artifacthub.io/docs/topics/cli"
      "org.opencontainers.image.source": "https://github.com/artifacthub/hub/tree/{{ .FullCommit }}/cmd/ah"
      "org.opencontainers.image.vendor": "Artifact Hub"
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/artifacthub/hub/{{ .FullCommit }}/docs/cli.md"
      "io.artifacthub.package.maintainers": '[{"name":"Artifact Hub maintainers","email":"cncf-artifacthub-maintainers@lists.cncf.io"}]'
      "io.artifacthub.package.logo-url": "https://raw.githubusercontent.com/artifacthub/hub/master/docs/logo/logo.svg"
      "io.artifacthub.package.keywords": "artifact hub,cli,lint"
      "io.artifacthub.package.license": "Apache-2.0"
      "io.artifacthub.package.alternative-locations": "public.ecr.aws/artifacthub/ah:{{ .Tag }}"
    extra_files:
      - go.mod
      - go.sum
      - cmd/ah
      - internal
  - id: db-migrator
    dockerfile: database/migrations/Dockerfile
    images:
      - artifacthub/db-migrator
      - public.ecr.aws/artifacthub/db-migrator
    tags:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - database/migrations
  - id: hub
    dockerfile: cmd/hub/Dockerfile
    images:
      - artifacthub/hub
      - public.ecr.aws/artifacthub/hub
    tags:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - go.mod
      - go.sum
      - cmd/hub
      - docs
      - internal
      - scripts
      - web
      - widget
  - id: scanner
    dockerfile: cmd/scanner/Dockerfile
    images:
      - artifacthub/scanner
      - public.ecr.aws/artifacthub/scanner
    tags:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - go.mod
      - go.sum
      - cmd/scanner
      - internal
  - id: tracker
    dockerfile: cmd/tracker/Dockerfile
    images:
      - artifacthub/tracker
      - public.ecr.aws/artifacthub/tracker
    tags:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - go.mod
      - go.sum
      - cmd/tracker
      - internal
      - ml

homebrew_casks:
  - name: ah
    description: Artifact Hub command line tool
    homepage: https://github.com/artifacthub/hub
    license: Apache-2.0
    repository:
      owner: artifacthub
      name: homebrew-cmd
    commit_author:
      name: artifacthubio
      email: hub@artifacthub.io
    binary: ah
    conflicts:
      - formula: ah
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ah"]
          end

scoops:
  - description: Artifact Hub command line tool
    homepage: https://github.com/artifacthub/hub
    license: Apache-2.0
    repository:
      owner: artifacthub
      name: scoop-cmd
    commit_author:
      name: artifacthubio
      email: hub@artifacthub.io

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

sboms:
  - artifacts: archive
