apiVersion: v1
kind: Secret
metadata:
  name: chart-tracker-config
type: Opaque
stringData:
  chart-tracker.yaml: |-
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      url: {{ .Values.db.url }}
    tracker:
      numWorkers: {{ .Values.chartTracker.numWorkers }}
      repositoriesNames: {{ .Values.chartTracker.repositories }}
