apiVersion: v1
kind: Secret
metadata:
  name: chart-tracker-config
type: Opaque
stringData:
  chart-tracker.yaml: |-
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      host: {{ .Values.db.host }}
      port: {{ .Values.db.port }}
      database: {{ .Values.db.database }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    tracker:
      numWorkers: {{ .Values.chartTracker.numWorkers }}
      repositoriesNames: {{ .Values.chartTracker.repositories }}
      imageStore: {{ .Values.chartTracker.imageStore }}
