apiVersion: v1
kind: Secret
metadata:
  name: db-migrator-config
type: Opaque
stringData:
  tern.conf: |-
    [database]
    host = {{ .Values.db.host }}
    port = {{ .Values.db.port }}
    database = {{ .Values.db.database }}
    user = {{ .Values.db.user }}
    password = {{ .Values.db.password }}

    [data]
    loadSampleData = {{ .Values.dbMigrator.loadSampleData }}
