apiVersion: v1
kind: Secret
metadata:
  name: hub-config
type: Opaque
stringData:
  hub.yaml: |-
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      url: {{ .Values.db.url }}
    server:
      addr: 0.0.0.0:8000
      shutdownTimeout: 30s
      webBuildPath: ./web
