apiVersion: v1
kind: Secret
metadata:
  name: hub-config
type: Opaque
stringData:
  hub.yaml: |-
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      host: {{ .Values.db.host }}
      port: {{ .Values.db.port }}
      database: {{ .Values.db.database }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    server:
      addr: 0.0.0.0:8000
      shutdownTimeout: 30s
      webBuildPath: ./web
      basicAuth:
        enabled: {{ .Values.hub.server.basicAuth.enabled }}
        username: {{ .Values.hub.server.basicAuth.username }}
        password: {{ .Values.hub.server.basicAuth.password }}
      cookie:
        hashKey: {{ .Values.hub.server.cookie.hashKey }}
        secure: {{ .Values.hub.server.cookie.secure }}
    email:
      fromName: {{ .Values.hub.email.fromName }}
      from: {{ .Values.hub.email.from }}
      replyTo: {{ .Values.hub.email.replyTo }}
      smtp:
        host: {{ .Values.hub.email.smtp.host }}
        port: {{ .Values.hub.email.smtp.port }}
        username: {{ .Values.hub.email.smtp.username }}
        password: {{ .Values.hub.email.smtp.password }}

