apiVersion: v1
kind: Secret
metadata:
  name: opa-tracker-config
type: Opaque
stringData:
  opa-tracker.yaml: |-
    log:
      level: {{ .Values.log.level }}
      pretty: {{ .Values.log.pretty }}
    db:
      host: {{ .Values.db.host }}
      port: {{ .Values.db.port }}
      database: {{ .Values.db.database }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    tracker:
      concurrency: {{ .Values.opaTracker.concurrency }}
      repositoriesNames: {{ .Values.opaTracker.repositories }}
      imageStore: {{ .Values.opaTracker.imageStore }}
      bypassDigestCheck: {{ .Values.opaTracker.bypassDigestCheck }}
