drop function if exists get_image(p_image_id uuid, p_version text);
drop function if exists register_image(p_original_hash bytea, p_version text, p_data bytea);
drop function if exists get_packages_updates();
drop function if exists get_package(p_package_id uuid);
drop function if exists get_package_version(p_package_id uuid, p_version text);
drop function if exists search_packages(p_query jsonb);
drop function if exists get_stats();
drop function if exists register_package(p_pkg jsonb);
drop function if exists get_chart_repository_packages_digest(p_chart_repository_id uuid);
drop function if exists get_chart_repository_by_name(p_name text);
drop function if exists get_chart_repositories();
drop function if exists semver_gte(p_v1 text, p_v2 text);
