{
 "title": "ArtifactHub",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful requests processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{kubernetes_namespace=\"$environment\",path!=\"/\",status=\"OK\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{kubernetes_namespace=\"$environment\",path!=\"/\",status!=\"Internal Server Error\"}[$__interval])) / sum(rate(http_request_duration_count{kubernetes_namespace=\"$environment\",path!=\"/\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Failed requests processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{kubernetes_namespace=\"$environment\",path!=\"/\",status=\"Internal Server Error\"}[$__interval]))"
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "API average latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_sum{kubernetes_namespace=\"$environment\",path=~\"/api/v1/.*\",status=\"OK\"}[$__interval])) / sum(rate(http_request_duration_count{kubernetes_namespace=\"$environment\",path=~\"/api/v1/.*\",status=\"OK\"}[$__interval]))",
     "legendFormat": "API average latency"
    }
   ]
  },
  { "title": "Requests rate (per second)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Successful requests rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"OK\"}[$__interval])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"Internal Server Error\"}[$__interval])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "Requests duration (in seconds)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Successful requests duration (p95)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"OK\"}[$__interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p95)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"Internal Server Error\"}[$__interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Successful requests duration (p75)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_bucket{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"OK\"}[$__interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p75)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_bucket{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"Internal Server Error\"}[$__interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Successful requests duration (p50)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_bucket{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"OK\"}[$__interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p50)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_bucket{kubernetes_namespace=\"$environment\",path!=\"/\",path!=\"\",status=\"Internal Server Error\"}[$__interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}