log:
  level: debug
  pretty: true
db:
  url: postgres://postgres@localhost:5432/hub
server:
  addr: localhost:8000
  shutdownTimeout: 1m
  webBuildPath: ../../web/build
  basicAuth:
    enabled: true
    username: hub
    password: changeme
