log:
  level: debug
  pretty: true
db:
  host: localhost
  port: "5432"
  database: hub
  user: postgres
server:
  addr: localhost:8000
  shutdownTimeout: 1m
  webBuildPath: ../../web/build
  basicAuth:
    enabled: false
    username: hub
    password: changeme
